### ISSUE TITLE
RT

### ISSUE THREAD

**Issue by HY-Vae** [ChellyLau/MediaUnitedKit#2]
![image](https://user-images.githubusercontent.com/18542402/40347470-062551e0-5dd3-11e8-96f7-f543c78b34f6.png)

**Comment by CheeryLau** [comment]
已经更新。

**Comment by ChellyLau** [comment]
> Sorry...刚回复你，code已经更新，请使用最新code。

Sorry...刚回复你，code已经更新，请使用最新code。

**Comment by ChellyLau** [comment]
Sorry...刚回复你，code已经更新，请使用最新code。
